### ISSUE TITLE
Exception while saving new page with double resources

### ISSUE THREAD

**Issue by beligum** [republic-of-reinvention/com.stralo.framework#61]
This Exception:

```
2019-06-03 16:32:25,055 ERROR [c.b.b.s.e.AbstractExceptionHandler] Handling exception for HTTP status 500 (Internal Server Error) in error handler com.beligum.base.server.exceptionhandlers.GeneralExceptionHandler
Server context:
    start time: Mon Jun 03 16:16:20 CEST 2019
    booted: true
    runlevel: SERVER
    fingerprint: XPUrtA
Request context:
    Method: POST
    Request URI: http://localhost:8080/import/resource?url=%2Fresource%2F1135551166264938398%3Flang%3Den&resourceTypeCurie=crb%3AItem&baseResource=/resource/1135551166264938398
    User: 1:  Administrator <admin>
    Acceptable languages: *
    Acceptable media types: application/json
    Headers:
        Cookie = [$Version=1;JSESSIONID=node0eeru6m8exbfb12iuozezzlqx80.node0]
        Accept = [application/json]
        Cache-Control = [no-cache]
        User-Agent = [Jersey/2.12 (HttpUrlConnection 1.8.0_201)]
        Connection = [keep-alive]
        Host = [localhost:8080]
        Pragma = [no-cache]
        Content-Length = [4648]
        Content-Type = [application/json]
Remote context:
    User:  Administrator
    Address: 127.0.0.1
    Host: 127.0.0.1
    Port: 43870
Error context:
    Status code: 500
    Status message: Internal Server Error
    Exception message: Error while updating a Solr resource; http://localhost:8080/resource/1135551166264938398
    Stacktrace: 
java.io.IOException: Error while updating a Solr resource; http://localhost:8080/resource/1135551166264938398
    at com.beligum.blocks.index.solr.SolrPageIndexConnection.update(SolrPageIndexConnection.java:178)
    at com.beligum.blocks.filesystem.pages.PageRepository.index(PageRepository.java:458)
    at com.beligum.blocks.filesystem.pages.PageRepository.index(PageRepository.java:452)
    at com.beligum.blocks.filesystem.pages.PageRepository.save(PageRepository.java:258)
    at com.beligum.base.resources.ResourceManager.save(ResourceManager.java:207)
    at com.beligum.base.resources.ResourceManager.save(ResourceManager.java:223)
    at com.beligum.blocks.endpoints.PageAdminEndpoint.savePage(PageAdminEndpoint.java:367)
    at com.beligum.cinematek.filmout.site.endpoint.ImportEndpoint.importResource(ImportEndpoint.java:226)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
    at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
    at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
    at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
    at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:502)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.client.solrj.SolrServerException: java.lang.RuntimeException: crb:date_proxy has a parent node at my level or lower
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:233)
    at org.apache.solr.client.solrj.SolrClient.request(SolrClient.java:1264)
    at com.beligum.blocks.index.solr.SolrPageIndexConnection.updateJsonDoc(SolrPageIndexConnection.java:550)
    at com.beligum.blocks.index.solr.SolrPageIndexConnection.update(SolrPageIndexConnection.java:175)
    ... 67 common frames omitted
Caused by: org.apache.solr.client.solrj.SolrServerException: java.lang.RuntimeException: crb:date_proxy has a parent node at my level or lower
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.checkForExceptions(EmbeddedSolrServer.java:301)
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:192)
    ... 70 common frames omitted
Caused by: java.lang.RuntimeException: crb:date_proxy has a parent node at my level or lower
    at org.apache.solr.common.util.JsonRecordReader$Node.setAsRecord(JsonRecordReader.java:183)
    at org.apache.solr.common.util.JsonRecordReader$Node.build(JsonRecordReader.java:246)
    at org.apache.solr.common.util.JsonRecordReader$Node.access$000(JsonRecordReader.java:155)
    at org.apache.solr.common.util.JsonRecordReader.addField(JsonRecordReader.java:108)
    at org.apache.solr.common.util.JsonRecordReader.addSplit(JsonRecordReader.java:83)
    at org.apache.solr.common.util.JsonRecordReader.getInst(JsonRecordReader.java:40)
    at org.apache.solr.handler.loader.JsonLoader$SingleThreadedJsonLoader.handleSplitMode(JsonLoader.java:218)
    at org.apache.solr.handler.loader.JsonLoader$SingleThreadedJsonLoader.processUpdate(JsonLoader.java:136)
    at org.apache.solr.handler.loader.JsonLoader$SingleThreadedJsonLoader.load(JsonLoader.java:121)
    at org.apache.solr.handler.loader.JsonLoader.load(JsonLoader.java:84)
    at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
    at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:2559)
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:191)
    ... 70 common frames omitted
2019-06-03 16:32:25,061 INFO  [o.a.s.u.DirectUpdateHandler2] start rollback{}
2019-06-03 16:32:25,073 INFO  [o.a.s.u.DefaultSolrCoreState] New IndexWriter is ready to be used.
2019-06-03 16:32:25,073 INFO  [o.a.s.u.DirectUpdateHandler2] end_rollback
```

For this HTML:

```
<div class="col-md-11">
    <blocks-fact-entry>
        <div data-property="name"><p>identifier</p></div>
        <div data-property="value">
            <div class="property number" property="crb:numericIdentifier" datatype="xsd:int" content="179544">179544</div>
        </div>
    </blocks-fact-entry>
    <blocks-fact-entry>
        <div data-property="name"><p>element type</p></div>
        <div data-property="value">
            <div class="property resource" property="crb:elementType" resource="/resource/ElementType/positive" content="/resource/ElementType/positive"><a
                    href="/resource/ElementType/positive?lang=en">positive</a></div>
        </div>
    </blocks-fact-entry>
    <blocks-fact-entry>
        <div data-property="name"><p>duration</p></div>
        <div data-property="value">
            <div class="property object" property="crb:duration" typeof="crb:Duration" resource="/resource/1135554190902095190">
                <div><label>note</label>
                    <div class="property editor" property="crb:note" datatype="rdf:HTML">164 '</div>
                </div>
                <div><label>label</label>
                    <div class="property inline-editor" property="rdfs:label">duration</div>
                </div>
            </div>
        </div>
    </blocks-fact-entry>
    <blocks-fact-entry>
        <div data-property="name"><p>sound</p></div>
        <div data-property="value">
            <div class="property boolean" property="crb:sound" datatype="xsd:boolean" content="true">
                <div class="value"></div>
            </div>
        </div>
    </blocks-fact-entry>
    <blocks-fact-entry>
        <div data-property="name"><p>date</p></div>
        <div data-property="value">
            <div class="property object" property="crb:date" typeof="crb:Date" resource="/resource/1135554190902873846">
                <div class="main"><label>start date</label>
                    <div class="property date" property="crb:startDate" datatype="xsd:date" content="2015-02-18">Thursday February 19, 2015</div>
                </div>
                <div>
                    <label>end date</label>
                    <div class="property date" property="crb:endDate" datatype="xsd:date" content="2015-02-18">Thursday February 19, 2015</div>
                </div>
                <div>
                    <label>precision</label>
                    <div class="property resource" property="crb:precision" content="/resource/Precision/certain" resource="/resource/Precision/certain"><a href="/resource/Precision/certain">certain</a>
                    </div>
                </div>
                <div><label>date type</label>
                    <div class="property resource" property="crb:dateType" content="/resource/DateType/acquisition" resource="/resource/DateType/acquisition"><a
                            href="/resource/DateType/acquisition">acquisition</a></div>
                </div>
            </div>
        </div>
    </blocks-fact-entry>
    <blocks-fact-entry class="double">
        <div data-property="name"><p>date</p></div>
        <div data-property="value">
            <div class="property object" property="crb:date" typeof="crb:Date" resource="/resource/1135554190899340481">
                <div class="main"><label>start date</label>
                    <div class="property date" property="crb:startDate" datatype="xsd:date" content="2017-10-09">Tuesday October 10, 2017</div>
                </div>
                <div><label>end date</label>
                    <div class="property date" property="crb:endDate" datatype="xsd:date" content="2017-10-09">Tuesday October 10, 2017</div>
                </div>
                <div><label>precision</label>
                    <div class="property resource" property="crb:precision" content="/resource/Precision/certain" resource="/resource/Precision/certain"><a href="/resource/Precision/certain">certain</a>
                    </div>
                </div>
                <div><label>date type</label>
                    <div class="property resource" property="crb:dateType" content="/resource/DateType/creation" resource="/resource/DateType/creation"><a href="/resource/DateType/creation">creation</a>
                    </div>
                </div>
            </div>
        </div>
    </blocks-fact-entry>
    <blocks-fact-entry>
        <div data-property="name"><p>sound combined or separate</p></div>
        <div data-property="value">
            <div class="property resource" property="crb:soundCombinedSeparate" resource="/resource/SoundCombinedOrSeparate/combined" content="/resource/SoundCombinedOrSeparate/combined"><a
                    href="/resource/SoundCombinedOrSeparate/combined?lang=en">combined</a></div>
        </div>
    </blocks-fact-entry>
    <blocks-fact-entry>
        <div data-property="name"><p>description</p></div>
        <div data-property="value">
            <div class="property editor" property="crb:description" datatype="rdf:HTML">Fu rong zhen</div>
        </div>
    </blocks-fact-entry>
</div>
```

**Comment by beligum** [comment]
Solr doesn't allow double entries in the split path parameter
